#!/bin/bash
set -euo pipefail
BUCKET=$1
KEY=$2
SQS_QUEUE=$3

cat <<EOF | aws sqs send-message --queue-url "$SQS_QUEUE" --message-body file:///dev/stdin
{
  "Records": [
    {
      "eventVersion": "2.1",
      "eventSource": "aws:s3",
      "awsRegion": "<AWS_REGION>",
      "eventTime": "<EVENT_TIME>",
      "eventName": "ObjectCreated:Put",
      "userIdentity": {
        "principalId": "AWS:ABCD"
      },
      "requestParameters": {
        "sourceIPAddress": "1.2.3.4"
      },
      "responseElements": {
        "x-amz-request-id": "2342",
        "x-amz-id-2": "foo"
      },
      "s3": {
        "s3SchemaVersion": "1.0",
        "configurationId": "testConfigRule",
        "bucket": {
          "name": "$BUCKET",
          "ownerIdentity": {
            "principalId": "ABCD"
          },
          "arn": "arn:aws:s3:::$BUCKET"
        },
        "object": {
          "key": "$KEY",
          "size": 1024,
          "eTag": "$RANDOM",
          "sequencer": "0ABCDEFGH123456789"
        }
      }
    }
  ]
}
EOF
