apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamer
  name: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: streamer
      volumes:
      - name: hooks
        configMap:
          name: streamer-hooks
          defaultMode: 0755
      containers:
      - image: PLACEHOLDER
        name: streamer
        resources:
          limits:
            memory: 180Mi
        volumeMounts:
        - name: hooks
          mountPath: /tmp/hooks.d
          readOnly: true
        env:
        - name: SQS_QUEUE
          valueFrom:
            secretKeyRef:
              name: streamer
              key: sqs_queue
        - name: AWS_DEFAULT_REGION
          value: us-west-2
        - name: OUTPUT_URL
          valueFrom:
            secretKeyRef:
              name: streamer
              key: output_url
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: streamer
              key: auth_token
