#!/bin/bash
set -euo pipefail
NAMESPACE="$1"
IMAGE="$2"

yaml2json deploy/deployment.yaml \
    | jq --arg image "$IMAGE" '.spec.template.spec.containers[0].image = $image' \
    | kubectl apply --namespace="$NAMESPACE" -f -
kubectl apply --namespace="$NAMESPACE" -f deploy/serviceaccount.yaml
