apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamer
  name: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer
  template:
    metadata:
      labels:
        app: streamer
    volumes:
    - name: assets
      hostPath:
        path: /var/lib/rancher/k3s/diambra/assets
        readOnly: true
    - name: input
      hostPath:
        path: /var/lib/rancher/k3s/diambra/output
        readOnly: true
    - name: archive
      hostPath:
        path: /var/lib/rancher/k3s/diambra/archive
    spec:
      containers:
      - image: PLACEHOLDER
        name: streamer
        resources:
          limits:
            memory: 120Mi
        volumeMounts:
        - mountPath: /assets
          name: assets
        - mountPath: /input
          name: input
        - mountPath: /archive
          name: archive
