name: default

on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  build_and_deploy:
    uses: diambra/gh-actions/.github/workflows/build-and-deploy.yaml@main
    with:
      deploy: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
    secrets: inherit
